channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=22.0.2
- pip:
  - mlflow==2.16.0
  - cffi==1.17.0
  - cloudpickle==3.0.0
  - defusedxml==0.7.1
  - pandas==2.2.2
  - psutil==6.0.0
  - scikit-learn==1.5.1
name: mlflow-env
